#ifndef MALIQUIZLIB_GLOBAL_H
#define MALIQUIZLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MALIQUIZLIB_LIBRARY)
#  define MALIQUIZLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MALIQUIZLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MALIQUIZLIB_GLOBAL_H
